---
- hosts: ambari
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
    java_archive: /tmp/jdk-8u151-linux-x64.tar.gz
    java_name: /usr/java/jdk1.8.0_151
  name: install and configure ambari
  tasks:
#   - include_role:
#       name: oracle_java8  
    - name: install ambari
      become: yes
      become_method: sudo
      command:  yum -y install ambari-server
    - name: run ambari-server setup
      become: yes
      become_method: sudo
      shell: echo -e "y\nn\n1\ny\nn\nn\n" | ambari-server setup
#     command: echo -e "y\nn\n1\ny\nn\nn\n" | ambari-server setup
      register: ambari_setup
    - debug: var=ambari_setup.stdout_lines
#   - debug: msg="{{ ambari_setup.stdout }}"
#   - debug: msg="{{ ambari_setup.stderr }}"
