---
- hosts: all
  name: Run on all machines
  tasks:
    - name: install libselinux-python
      become: yes
      become_method: sudo
      yum:
        name: libselinux-python
        state: present
    - name: install ntp
      become: yes
      become_method: sudo
      command:  yum install -y ntp

    - name: ensure ntp always started
      become: yes
      become_method: sudo
      command: chkconfig ntpd on
    - name: set to local ntp server
      become: yes
      become_method: sudo
      lineinfile:
        dest: /etc/ntp.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: 'server 0.centos.pool.ntp.org iburst',line:'#server 0.centos.pool.ntp.org iburst'}
        - { regexp: 'server 1.centos.pool.ntp.org iburst',line:'#server 1.centos.pool.ntp.org iburst'}
        - { regexp: 'server 2.centos.pool.ntp.org iburst',line:'#server 2.centos.pool.ntp.org iburst'}
        - { regexp: 'server 3.centos.pool.ntp.org iburst',line:'#server 3.centos.pool.ntp.org iburst\nserver ambari.hdpdev.com iburst'}
#       dest: /etc/sysctl.conf
#       regexp: "{{ item.regexp }}"
#       line: "{{ item.line }}"
#     with_items:
#       - { regexp: '^kernel.shmall', line: 'kernel.shmall = 2097152' }
#       - { regexp: '^kernel.shmmax', line: 'kernel.shmmax = 134217728' }
#       - { regexp: '^fs.file-max', line: 'fs.file-max = 65536' }
    - name: disable transparent huge pages
      become: yes
      become_method: sudo
      shell: "{{ item }}" 
      with_items:
        - echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled
        - echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag
#     register: disable_thp
#     ignore_errors: true
#   - debug: var=disable_thp.stdout_lines
    - name: addresss localhost issue
      become: yes
      become_method: sudo
      lineinfile:
        dest: /etc/hosts
#       path: /etc/hosts    #Only good for Ansible > 2.3, use dest= for Ansible < 2.3
        regexp: '^127\.0\.0\.1'
        line: '#127.0.0.1'
        owner: root
        group: root
        mode: 0644
