---
- hosts: hdptest
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
    java_archive: /tmp/jdk-8u151-linux-x64.tar.gz
    java_name: /usr/java/jdk1.8.0_151
  name: experimental deployment
  tasks:
    - name: oracle java 8
      static: no
      include_role:
        name: oracle_java8
