---
- hosts: hdptest
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
    java_archive: /opt/jdk-8u151-linux-x64.tar.gz
    java_name: /usr/java/jdk1.8.0_151
    namenode_dirs: /grid/hadoop/hdfs/nn
    secondary_namenode_dirs: /grid/hadoop/hdfs/snn
    data_dirs: /grid/hadoop/hdfs/dn
    yarn_local_dirs: /grid/hadoop/yarn/local 
    yarn_local_log_dirs: /grid/hadoop/yarn/logs
    zookeeper_data_dirs: /grid/hadoop/zookeeper/data
    
  name: experimental deployment
  tasks:
    - name: install oracle java 8 and set JCE8 crypto policy to unlimited
      static: no
      include_role:
        name: oracle_java8

    - name: add HDP 2.6.3.x repo
      become: yes
      become_method: sudo
      yum_repository:
        name: HDP2.6
        description: Hortonworks HDP 2.6
#       baseurl: URL    http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.6.3.0
#        baseurl: "{{ item }}"
        baseurl: "http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.6.3.0"
        gpgcheck: no
        enabled: yes
#      with_items:
#        - "http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.6.3.0"
#        - "http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/centos6"
    - name: add HDP Utils repo
      become: yes
      become_method: sudo
      yum_repository:
        name: HDP2.6 Utils
        description: Hortonworks HDP 2.6 Utils
        baseurl: "http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/centos6"
        gpgcheck: no
        enabled: yes

    - name: install HDP base packages
      become: yes
      become_method: sudo
      yum:
        name: "{{item}}"
      with_items:
        - hadoop
        - hadoop-hdfs
        - hadoop-libhdfs
        - hadoop-yarn
        - hadoop-mapreduce
        - hadoop-client
        - openssl
     # install compression libraries
        - snappy
        - snappy-devel
        - lzo
        - lzo-devel
        - hadooplzo
        - hadooplzo-native

    - name: download HDP helper files
      become: yes
      become_method: sudo
      #command: wget -O /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8.tar.gz http://public-repo-1.hortonworks.com/HDP/tools/2.6.0.3/hdp_manual_install_rpm_helper_files-2.6.0.3.8.tar.gz
      get_url:
        url: http://public-repo-1.hortonworks.com/HDP/tools/2.6.0.3/hdp_manual_install_rpm_helper_files-2.6.0.3.8.tar.gz
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8.tar.gz
        mode: 0755

    - name: extract HDP helper files
      become: yes
      become_method: sudo
      command: tar xf hdp_manual_install_rpm_helper_files-2.6.0.3.8.tar.gz
      args:
        chdir: /opt

    - name: chamge permissions on helper files
      become: yes
      become_method: sudo
      command: chmod -R 755 /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts

    - name: NAMENODE variable injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-LIST-OF-NAMENODE-DIRS'
        line: 'DFS_NAME_DIR={{ namenode_dirs }}'
        state: present

    - name: SECONDARY NAMENODE variable injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-LIST-OF-SECONDARY-NAMENODE-DIRS'
        line: 'FS_CHECKPOINT_DIR={{ secondary_namenode_dirs }}'
        state: present

    - name: DATANODE variable injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-LIST-OF-DATA-DIRS'
        line: 'DFS_DATA_DIR={{ data_dirs }}'
        state: present

    - name: YARN LOCAL variable injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-LIST-OF-YARN-LOCAL-DIRS'
        line: 'YARN_LOCAL_DIR={{ yarn_local_dirs }}'
        state: present

    - name: YARN LOG variable injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-LIST-OF-YARN-LOCAL-LOG-DIRS'
        line: 'YARN_LOCAL_LOG_DIR={{ yarn_local_log_dirs }}'
        state: present

    - name: ZOOKEEPER variable injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-ZOOKEEPER-DATA-DIR'
        line: 'ZOOKEEPER_DATA_DIR={{ zookeeper_data_dirs }}'
        state: present

    - name: change ownership of HDP Helper directory
      become: yes
      become_method: sudo
      command: chown -R root:root /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8

    - name: set directories env variables
      become: yes
      become_method: sudo
      shell: . ~/.bashrc && . /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
      #command: source ./directories.sh
      #command: . /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
      #args:
      #  chdir: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts

    - name: set user variables
      become: yes
      become_method: sudo
      shell: . ~/.bashrc && . /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/usersAndGroups.sh
      #command: source ./usersAndGroups.sh
      #args:
      #  chdir: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts

    - name: printout environment variables
      debug: var=ansible_env

#- hosts: namenode
#  name: namenode only
#  tasks:

    - name: create namenode directories
      become: yes
      become_method: sudo
      command: mkdir -p $DFS_NAME_DIR

    - name: change ownership namenode directories
      become: yes
      become_method: sudo
      file:
        path: /grid/hadoop/hdfs/nn
        #path: $DFS_NAME_DIR
        owner: hdfs
        #owner: $HDFS_USER 
        group: hadoop
        #group: $HADOOP_GROUP
        mode: 0755    
        recurse: yes 
        state: directory

    - name: set java to Oracle JAVA
      become: yes
      become_method: sudo
      command: alternatives --set java /usr/java/jdk1.8.0_151/bin/java
#   - name: change ownership namenode directories
#     become: yes
#     become_method: sudo
#     command: chown -R $HDFS_USER:$HADOOP_GROUP $DFS_NAME_DIR

#   - name: change permissions namenode directories
#     become: yes
#     become_method: sudo
#     command: chmod -R 755 $DFS_NAME_DIR
 
    - name: create secondary namenode directories
      become: yes
      become_method: sudo
      command: mkdir -p $FS_CHECKPOINT_DIR
  
    - name: change ownership secondary namenode directories
      become: yes
      become_method: sudo
      file:
        path: /grid/hadoop/hdfs/snn
        #path: $DFS_NAME_DIR
        owner: hdfs
        #owner: $HDFS_USER 
        group: hadoop
        #group: $HADOOP_GROUP
        mode: 0755    
        recurse: yes 
        state: directory

#   - name: change ownership secondary namenode directories
#     become: yes
#     become_method: sudo
#     command: chown -R $HDFS_USER:$HADOOP_GROUP $FS_CHECKPOINT_DIR
    
#   - name: change permissions secondary namenode directories
#     become: yes
#     become_method: sudo
#     command: chmod -R 755 $FS_CHECKPOINT_DIR
 
    - name: create datanode directories
      become: yes
      become_method: sudo
      command: mkdir -p $DFS_DATA_DIR
   
    - name: change ownership datanode directories
      become: yes
      become_method: sudo
      file:
        path: /grid/hadoop/hdfs/dn
        #path: $DFS_NAME_DIR
        owner: hdfs
        #owner: $HDFS_USER 
        group: hadoop
        #group: $HADOOP_GROUP
        mode: 0755    
        recurse: yes 
        state: directory

#   - name: change ownership datanode directories
#     become: yes
#     become_method: sudo
#     command: chown -R $HDFS_USER:$HADOOP_GROUP $DFS_DATA_DIR

#   - name: change permissions datanode directories
#     become: yes
#     become_method: sudo
#     command: chmod -R 750 $DFS_DATA_DIR

#- hosts: ResourceManager and all Datanodes
    - name: create YARN directories
      become: yes
      become_method: sudo
      command: mkdir -p $YARN_LOCAL_DIR

    - name: change ownership YARN directories
      become: yes
      become_method: sudo
      file:
        path: /grid/hadoop/yarn/local
        #path: $YARN_LOCAL_DIR
        owner: yarn
        #owner: $YARN_USER 
        group: hadoop
        #group: $HADOOP_GROUP
        mode: 0755    
        recurse: yes 
        state: directory

#   - name: change ownernership of YARN directories
#     become: yes
#     become_method: sudo
#     command: chown -R $YARN_USER:$HADOOP_GROUP $YARN_LOCAL_DIR

#   - name: change permissions of YARN directories
#     become: yes
#     become_method: sudo
#     command: chmod -R 755 $YARN_LOCAL_DIR

# CREATE LOG and PID Directories
    - name: create log directories
      become: yes
      become_method: sudo
      command: mkdir -p $HDFS_LOG_DIR

    - name: change ownership LOG directories
      become: yes
      become_method: sudo
      file:
        path: /var/log/hadoop/hdfs
        #path: $HDFS_LOG_DIR
        owner: hdfs
        #owner: $HDFS_USER 
        group: hadoop
        #group: $HADOOP_GROUP
        mode: 0755    
        recurse: yes 
        state: directory

#   - name: change ownership of LOG directories
#     become: yes
#     become_method: sudo
#     command: chown -R $HDFS_USER:$HADOOP_GROUP $HDFS_LOG_DIR

#   - name: change permissions of LOG directories
#     become: yes
#     become_method: sudo
#     command: chmod -R 755 $HDFS_LOG_DIR

    - name: create YARN Logs Directories
      become: yes
      become_method: sudo
      command: mkdir -p $YARN_LOG_DIR

    - name: change ownership YARN LOG directories
      become: yes
      become_method: sudo
      file:
        path: /var/log/hadoop/yarn
        #path: $YARN_LOG_DIR
        owner: yarn
        #owner: $YARN_USER 
        group: hadoop
        #group: $HADOOP_GROUP
        mode: 0755    
        recurse: yes 
        state: directory

#   - name: change ownership YARN Logs Directories
#     become: yes
#     become_method: sudo
#     command: chown -R $YARN_USER:$HADOOP_GROUP $YARN_LOG_DIR

#   - name: change permissions YARN Logs Directories
#     become: yes
#     become_method: sudo
#     command: chmod -R 755 $YARN_LOG_DIR

# All Nodes
# HDFS Process
    - name: create HDFS Process Directories 
      become: yes
      become_method: sudo
      command: mkdir -p $HDFS_PID_DIR

    - name: change ownership HDFS PID directories
      become: yes
      become_method: sudo
      file:
        path: /var/run/hadoop/hdfs
        #path: $HDFS_LOG_DIR
        owner: hdfs
        #owner: $HDFS_USER 
        group: hadoop
        #group: $HADOOP_GROUP
        mode: 0755    
        recurse: yes 
        state: directory

#   - name: change ownership of HDFS Process Directories
#     become: yes
#     become_method: sudo
#     command: chown -R $HDFS_USER:$HDFS_GROUP $HDFS_PID_DIR

#   - name: change permissions of HDFS Process Directories
#     become: yes
#     become_method: sudo
#     command: chmod -R 755 $HDFS_PID_DIR

# YARN Process ID

    - name: create YARN Process Directories 
      become: yes
      become_method: sudo
      command: mkdir -p $YARN_PID_DIR

    - name: change ownership YARN PID directories
      become: yes
      become_method: sudo
      file:
        path: /var/run/hadoop/yarn
        #path: $YARN_PID_DIR
        owner: yarn
        #owner: $YARN_USER 
        group: hadoop
        #group: $HADOOP_GROUP
        mode: 0755    
        recurse: yes 
        state: directory

#   - name: change ownership of YARN Process Directories
#     become: yes
#     become_method: sudo
#     command: chown -R $YARN_USER:$HDFS_GROUP $YARN_PID_DIR

#   - name: change permissions of YARN Process Directories
#     become: yes
#     become_method: sudo
#     command: chmod -R 755 $YARN_PID_DIR

# JobHistory Log

    - name: create JobHistory Server LOGS Directories 
      become: yes
      become_method: sudo
      command: mkdir -p $MAPRED_LOG_DIR

    - name: change ownership JobHistory Server LOGS directories
      become: yes
      become_method: sudo
      file:
        path: /var/log/hadoop/mapred
        #path: $MAPRED_PID_DIR
        owner: mapred
        #owner: $MAPRED_USER 
        group: hadoop
        #group: $HADOOP_GROUP
        mode: 0755    
        recurse: yes 
        state: directory

#   - name: change ownership of JobHistory Server LOGS Directories
#     become: yes
#     become_method: sudo
#     command: chown -R $MAPRED_USER:$HDFS_GROUP $MAPRED_LOG_DIR

#   - name: change permissions of JobHistory Server LOGS Directories
#     become: yes
#     become_method: sudo
#     command: chmod -R 755 $MAPRED_LOG_DIR

# JobHistory Server Process ID

    - name: create JobHistory Server Process ID Directories 
      become: yes
      become_method: sudo
      command: mkdir -p $MAPRED_PID_DIR

    - name: change ownership JobHistory Server PID directories
      become: yes
      become_method: sudo
      file:
        path: /var/run/hadoop/mapred
        #path: $MAPRED_PID_DIR
        owner: mapred
        #owner: $MAPRED_USER 
        group: hadoop
        #group: $HADOOP_GROUP
        mode: 0755    
        recurse: yes 
        state: directory

#   - name: change ownership of JobHistory Server Process ID Directories
#     become: yes
#     become_method: sudo
#     command: chown -R $MAPRED_USER:$HDFS_GROUP $MAPRED_PID_DIR

#   - name: change permissions of JobHistory Server Process ID Directories
#     become: yes
#     become_method: sudo
#     command: chmod -R 755 $MAPRED_PID_DIR

