---
- hosts: hdp
  name: Install Core HDP 
  tasks:
    - name: 
      become: yes
      become_method: sudo
      shell: wget -nv http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.6.2.0/hdp.repo -O /etc/yum.repos.d/hdp.repo

    - name: install core hadoop
      become: yes
      become_method: sudo
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - hadoop
        - hadoop-hdfs
        - hadoop-libhdfs
        - hadoop-yarn
        - hadoop-mapreduce
        - hadoop-client
        - openssl
