---
- name: winAD01 test
  vars:
    - ansible_connection: winrm
    - ansible_user: administrator
    - ansible_password: vagrant
    - ansible_port: 5985
  hosts: windows
  tasks:
  - name: test module
    win_ping:
#    win_module:
#      name: test
