---
- hosts: hdptest
  name: regexp tasks
  vars:
    namenode_dirs: /hadoop/hdfs/nn
    secondary_namenode_dirs: /hadoop/hdfs/snn
    data_dirs: /hadoop/hdfs/dn
    yarn_local_dirs: /hadoop/yarn/local
    yarn_local_log_dirs: /hadoop/yarn/logs
    zookeeper_data_dirs: /hadoop/zookeeper/data

  tasks:
    - name: NAMENODE varialble injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-LIST-OF-NAMENODE-DIRS'
        line: 'DFS_NAME_DIR={{ namenode_dirs }}'
        state: present
  
    - name: SECONDARY NAMENODE varialble injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-LIST-OF-SECONDARY-NAMENODE-DIRS'
        line: 'FS_CHECKPOINT_DIR={{ secondary_namenode_dirs }}'
        state: present
 
    - name: DATANODE varialble injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-LIST-OF-DATA-DIRS'
        line: 'DFS_DATA_DIR={{ data_dirs }}'
        state: present
  
    - name: YARN LOCAL varialble injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-LIST-OF-YARN-LOCAL-DIRS'
        line: 'YARN_LOCAL_DIR={{ yarn_local_dirs }}'
        state: present
 
    - name: YARN LOG varialble injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-LIST-OF-YARN-LOCAL-LOG-DIRS'
        line: 'YARN_LOCAL_LOG_DIR={{ yarn_local_log_dirs }}'
        state: present

    - name: ZOOKEEPER varialble injection
      become: yes
      become_method: sudo
      lineinfile:
        dest: /opt/hdp_manual_install_rpm_helper_files-2.6.0.3.8/scripts/directories.sh
        regexp: 'TODO-ZOOKEEPER-DATA-DIR'
        line: 'ZOOKEEPER_DATA_DIR={{ zookeeper_data_dirs }}'
        state: present
  
