---
- name: set env variable JAVA_HOME
  become: yes
  become_method: sudo
  shell:  . ~/.bashrc && export JAVA_HOME=/usr/java/jdk1.8.0_151

- name: Run as user hdfs
  become: yes
  become_method: sudo
  become_user: hdfs
  command:  sudo -u hdfs /usr/hdp/current/hadoop-hdfs-secondarynamenode/../hadoop/sbin/hadoop-daemon.sh --config /etc/hadoop/conf start secondarynamenode

- name: Run as user yarn #if running Resource Manager on Secondary Namenode
  become: yes
  become_method: sudo
  become_user: yarn
  command:  sudo -u yarn /usr/hdp/2.6.3.0-235/hadoop-yarn/sbin/yarn-daemon.sh --config /etc/hadoop/conf start resourcemanager
